Add support for US SSN
NCATComp410/comp410_fall_2022 pull request #90
Opened 2022-10-18 20:06 UTC by DougGajda

Used Regex to help search for SSN within the given sentence. Used the AssertEqual statement to check if the function and my list match up.

2022-10-18 23:01 UTC, claesmk commented on pii_team_frost.py
> +    SSNRegex = re.compile(r'\d\d\d-\d\d-\d\d\d\d')
This works, however, \d\d\d can be shortened to \d{3} - similar for the other \d patterns you have

2022-10-18 23:37 UTC, claesmk commented on pii_team_frost.py
> +    MO = SSNRegex.search(text)
I'll add some additional comments here later when I get a chance

2022-10-19 00:39 UTC, DrHinton410 commented
OK
________________________________
From: claesmk ***@***.***>
Sent: Tuesday, October 18, 2022 7:37 PM
To: NCATComp410/comp410_fall_2022 ***@***.***>
Cc: Marlow Hinton ***@***.***>; Review requested ***@***.***>
Subject: Re: [NCATComp410/comp410_fall_2022] Add support for US SSN (PR #90)

USE CAUTION. This message is from outside of N.C. A&T.
________________________________

@claesmk commented on this pull request.

________________________________

In pii_team_frost.py<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCATComp410%2Fcomp410_fall_2022%2Fpull%2F90%23discussion_r998799857&data=05%7C01%7Cmhinton%40ncat.edu%7Ce3ec53d4a3a84854610708dab161b52b%7Cd844dd75a4d74b1fbd33bc0b1c796c38%7C0%7C0%7C638017330482717837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MzyogzyF2rDqHJ3I9JacHnIA2u5039nAk58B1NHQBEo%3D&reserved=0>:

> @@ -22,7 +22,11 @@ def find_amex(text) -> list:
 def find_us_ssn(text) -> list:
     """Finds all occurrences of a US social security number in a text string"""
     # match a 9 digit social security number
-    return []
+    SSNRegex = re.compile(r'\d\d\d-\d\d-\d\d\d\d')
+    MO = SSNRegex.search(text)


I'll add some additional comments here later when I get a chance

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNCATComp410%2Fcomp410_fall_2022%2Fpull%2F90%23pullrequestreview-1146638689&data=05%7C01%7Cmhinton%40ncat.edu%7Ce3ec53d4a3a84854610708dab161b52b%7Cd844dd75a4d74b1fbd33bc0b1c796c38%7C0%7C0%7C638017330482717837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cpyXh6t15eZMS0agAtdSRykwBAyxQbC4uSnV9aXSb0s%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPZXG4AWF6XJPHD4OFJFSETWD4YDHANCNFSM6AAAAAARIN4S5Y&data=05%7C01%7Cmhinton%40ncat.edu%7Ce3ec53d4a3a84854610708dab161b52b%7Cd844dd75a4d74b1fbd33bc0b1c796c38%7C0%7C0%7C638017330482874084%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PFTbYI3hcVbPaBEZnImGNhp%2BXAUaPiafbrhjCTtNvuQ%3D&reserved=0>.
You are receiving this because your review was requested.Message ID: ***@***.***>

------- NOTICE: This e-mail correspondence is subject to Public Records Law and may be disclosed to third parties. --------

2022-10-19 01:19 UTC, claesmk requested changes
Please see embedded comments

2022-10-21 00:55 UTC, claesmk commented
@DougGajda let me know if you have any questions

2022-10-24 18:11 UTC, claesmk commented on pii_team_frost.py
> +    return [MO]
This is no longer a match object - what you were calling MO - so your variable name probably shouldn't be MO.  You are still trying to return that as a list.  I would
```
return re.findall(r'\d{3}-\d{2}-\d{4}', text)
```

2022-10-24 18:13 UTC, claesmk requested changes
Please see comments you are still returning a list within a list

2022-10-25 02:16 UTC, claesmk approved these changes
Looks like this is working OK, so will approve.  Not sure why you needed some extra imports
```
from pickle import FALSE
from unittest import result
from types import NoneType
```

2022-10-25 02:16 UTC, merged